services:
  app:
    build: .
    container_name: norway_guide
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0